### PR TITLE
Added verilator 5.023 devel rev v5.020-164-g1481d3495

### PR DESCRIPTION
**Pull request by NadeemYaseen**
Pulling in the latest verilator after the fix of https://github.com/verilator/verilator/issues/4946

### CODE REVIEW

**Comment by NadeemYaseen** [comment]
@alaindargelas When we take it to Raptor level, we need to update FOEDAG as well. Previously I was creating symbolic links to make verilator exe work when relocated but now the verilator developer has made it easy to relocate its executable. So In FOEDAG, where we are invoking the verilator, we don't need to set VERILATOR_ROOT anymore and need to invoke the verilator from `HDL_simulator/verilator/share/verilator/bin`

**Comment by alaindargelas** [comment]
@NadeemYaseen but the latest Verilator has a functional error, that is why we asked you to revert it back last week.
Please make sure an issue was filed for the functional error. We need it fixed before we can move forward with this update.

**Comment by alaindargelas** [comment]
@NadeemYaseen , looke like the issue is fixed:
https://github.com/verilator/verilator/issues/4946 so we can upgrade.
Which PR from FOEDAG needs to be in sync?

**Comment by NadeemYaseen** [comment]
> @NadeemYaseen , looke like the issue is fixed: [verilator/verilator#4946](https://github.com/verilator/verilator/issues/4946) so we can upgrade. Which PR from FOEDAG needs to be in sync?

@alaindargelas After the issue was fixed, I created this PR. But along with bringing in the fix of the issue, they also have merged this PR https://github.com/verilator/verilator/pull/4927 with which now VERILATOR_ROOT is handled by their wrapper script correctly when relocating binaries. 
I will work on FOEDAG to see if I can push a fix.

**Pull request merged**
