### PR TITLE
propagate CMAKE_CXX_FLAGS "no warnings" to partitioner

### PR DESCRIPTION
**Pull request by serge-dsa**
Attempting to suppress tons of KHP warnings in workflow logs

### CODE REVIEW

**Comment by serge-dsa** [comment]
@alaindargelas @manadher @NadeemYaseen 
FYI, it's not possible to merge without an approving review. I thought it was like Backend, review-optional..

**Comment by alaindargelas** [comment]
@serge-dsa It is not working:

/home/alain/os-fpga/Raptor/build/Raptor_Tools/graph_partition/mt-kahypar/external_tools/tbb/include/tbb/../oneapi/tbb/detail/_config.h:51:5: warning: "__INTEL_COMPILER" is not defined, evaluates to 0 [-Wundef]
   51 | #if __INTEL_COMPILER || _MSC_VER
      |     ^~~~~~~~~~~~~~~~
/home/alain/os-fpga/Raptor/build/Raptor_Tools/graph_partition/mt-kahypar/external_tools/tbb/include/tbb/../oneapi/tbb/detail/_config.h:51:25: warning: "_MSC_VER" is not defined, evaluates to 0 [-Wundef]
   51 | #if __INTEL_COMPILER || _MSC_VER
      |                         ^~~~~~~~
/home/alain/os-fpga/Raptor/build/Raptor_Tools/graph_partition/mt-kahypar/external_tools/tbb/include/tbb/../oneapi/tbb/detail/_config.h:77:7: warning: "__GLIBCPP__" is not defined, evaluates to 0 [-Wundef]
   77 | #elif __GLIBCPP__ || __GLIBCXX__
      |       ^~~~~~~~~~~
/home/alain/os-fpga/Raptor/build/Raptor_Tools/graph_partition/mt-kahypar/external_tools/tbb/include/tbb/../oneapi/tbb/detail/_config.h:82:5: warning: "__clang__" is not defined, evaluates to 0 [-Wundef]
   82 | #if __clang__
      |     ^~~~~~~~~
/home/alain/os-fpga/Raptor/build/Raptor_Tools/graph_partition/mt-kahypar/external_tools/tbb/include/tbb/../oneapi/tbb/detail/_config.h:97:5: warning: "_M_X64" is not defined, evaluates to 0 [-Wundef]
   97 | #if _M_X64 || _M_ARM64
      |     ^~~~~~

**Comment by alaindargelas** [comment]
Moreover it somehow breaks incremental compile.
After this merge, 
Raptor>make 
recompiles all the backend systematically.

It does not work with ccache

@serge-dsa , please retest, make sure you have **ccache** installed.
If there are steps required to purge the cache so this works properly, please specify.

**Comment by serge-dsa** [comment]
@alaindargelas OK. Failed attempt. I did not have these warnings in my local build even before. My previous fix for this issue eliminated the warnings for my local build, but not for github workflows.
@NadeemYaseen you may want to look into this problem when time permits.

**Pull request merged**
